In [1]:
import numpy as np

In [5]:
#creating single dimension array

In [6]:
a=np.array([1,34,2,4,12,3,23])

In [7]:
#another 1d array
b=np.array([44,77,1,88])

In [8]:
a

array([ 1, 34,  2,  4, 12,  3, 23])

In [9]:
b

array([44, 77,  1, 88])

In [10]:
#creating 2d array
x=np.array([[2,66],[33,8]])

In [11]:
x

array([[ 2, 66],
       [33,  8]])

In [12]:
x=np.array([[2,66],[33,8],[1,2],[4,5]])

In [13]:
x

array([[ 2, 66],
       [33,  8],
       [ 1,  2],
       [ 4,  5]])

In [15]:
x[0][1]

66

In [17]:
x[0][2]

IndexError: index 2 is out of bounds for axis 0 with size 2

In [18]:
#range of row
x[0:2]

array([[ 2, 66],
       [33,  8]])

In [ ]:
x*3

In [19]:
x**3


array([[     8, 287496],
       [ 35937,    512],
       [     1,      8],
       [    64,    125]])

In [23]:
#to find dimension
x.shape

(4, 2)

In [24]:
x.reverse()

AttributeError: 'numpy.ndarray' object has no attribute 'reverse'

In [25]:
x.reshape(2,4)

array([[ 2, 66, 33,  8],
       [ 1,  2,  4,  5]])

In [26]:
x.reshape(2,2)

ValueError: cannot reshape array of size 8 into shape (2,2)

In [31]:
y=x.reshape(4,2)

In [30]:
x

array([[ 2, 66],
       [33,  8],
       [ 1,  2],
       [ 4,  5]])

In [32]:
y[0:,1]

array([66,  8,  2,  5])

In [33]:
y[:,1]

array([66,  8,  2,  5])

In [34]:
y

array([[ 2, 66],
       [33,  8],
       [ 1,  2],
       [ 4,  5]])

In [37]:
y=y.reshape(2,4)

In [38]:
y

array([[ 2, 66, 33,  8],
       [ 1,  2,  4,  5]])

In [39]:
y[0:,2]

array([33,  4])

In [40]:
y[0:,1:]

array([[66, 33,  8],
       [ 2,  4,  5]])

In [47]:
a=np.zeros([4,4])

In [48]:
a

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [49]:
np.ones([3,3])

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [51]:
np.full([3,3],6)

array([[6, 6, 6],
       [6, 6, 6],
       [6, 6, 6]])

In [52]:
np.ones([5,5],dtype='int32')

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]], dtype=int32)

In [58]:
np.add(x,y.reshape(4,2))

array([[  4, 132],
       [ 66,  16],
       [  2,   4],
       [  8,  10]])

In [54]:


x

array([[ 2, 66],
       [33,  8],
       [ 1,  2],
       [ 4,  5]])

In [ ]:
x=